name: RELEASE

on:
  release:
    types: [created]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Pull project
        uses: actions/checkout@v2

      - name: Send project to remote server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: .
          remote: /var/www/MProject/Release
          host: ${{ secrets.MP_SSH_HOST }}
          port: ${{ secrets.MP_SSH_PORT }}
          username: root
          privateKey: ${{ secrets.MP_SSH_KEY }}

      - name: Rebuild and Restart containers
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /var/www/MProject/Release/deployment
            docker-compose -f release.yml build
            docker-compose -f release.yml up -d
          host: ${{ secrets.MP_SSH_HOST }}
          port: ${{ secrets.MP_SSH_PORT }}
          username: root
          privateKey: ${{ secrets.MP_SSH_KEY }}
